### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
turn into markdown

### CODE REVIEW

**Comment by Alan-R** [comment]
There's a little more to it than this. This particular file is involved with the Doxygen documentation build process, and the end result (readme.html) is pointed to by other things in the web site.

**Comment by h4ck3rm1k3** [comment]
ok, well I would at least add a markdown readme for github then.

**Comment by h4ck3rm1k3** [comment]
Alan, this should meet your requirements.

**Comment by Alan-R** [comment]
Did you test making the documentation, and verify that the link on the home page for the web site points to the new README? I don't see any evidence you changed either GettingStarted.c or MainPage.c.

This probably wasn't clear: We generate the open source web site from Doxygen. All the web site contents come from the docfiles directory. In particular, the GettingStarted.c and MainPage.c files point to the README file. The URL of that file no doubt changed when you changed its name.

Although these files end in .c, they consist only of comments, which are then processed by Doxygen. You probably need to tweak something to make your new file work on the web site as well.

The other lines of concern are:
CMakeLists.txt:set (CPACK_PACKAGE_RESOURCE_FILE_README ${CMAKE_CURRENT_SOURCE_DIR}/README)
Doxyfile.in:INPUT                  = @CMAKE_CURRENT_SOURCE_DIR@ @CMAKE_CURRENT_SOURCE_DIR@/README @CMAKE_CURRENT_BINARY_DIR@/include

**Comment by h4ck3rm1k3** [comment]
yes I ran make doc and checked the main page.I updated the link. Let me
check those mentioned. I found 3 more stragglers, please check now.

On Wed, Sep 16, 2015 at 12:27 PM, Alan Robertson <notifications@github.com>
wrote:

> Did you test making the documentation, and verify that the link on the
> home page for the web site points to the new README? I don't see any
> evidence you changed either GettingStarted.c or MainPage.c.
>
> This probably wasn't clear: We generate the open source web site from
> Doxygen. All the web site contents come from the docfiles directory. In
> particular, the GettingStarted.c and MainPage.c files point to the README
> file. The URL of that file no doubt changed when you changed its name.
>
> Although these files end in .c, they consist only of comments, which are
> then processed by Doxygen. You probably need to tweak something to make
> your new file work on the web site as well.
>
> The other lines of concern are:
> CMakeLists.txt:set (CPACK_PACKAGE_RESOURCE_FILE_README
> ${CMAKE_CURRENT_SOURCE_DIR}/README)
> Doxyfile.in:INPUT = @CMAKE_CURRENT_SOURCE_DIR@ @CMAKE_CURRENT_SOURCE_DIR@/README
> @CMAKE_CURRENT_BINARY_DIR@/include
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/pull/1#issuecomment-140794414>
> .
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by borgified** [comment]
sorry i tried to fix the conflict to help out but i gave up... i couldn't validate some of the changes you made. maybe start over with a clean checkout of the current master and reapply your changes on top of that, then create a new PR.

**Comment by h4ck3rm1k3** [comment]
I can just rebase, it should not be a problem. we dont need a new pr.

On Sat, Sep 19, 2015 at 1:24 PM, Fwiffo <notifications@github.com> wrote:

> sorry i tried to fix the conflict to help out but i gave up... i couldn't
> validate some of the changes you made. maybe start over with a clean
> checkout of the current master and reapply your changes on top of that,
> then create a new PR.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/pull/1#issuecomment-141691072>
> .
>



-- 
James Michael DuPont
Kansas Linux Fest http://kansaslinuxfest.us
Free/Libre Open Source and Open Knowledge Association of Kansas
http://openkansas.us
Member of Free Libre Open Source Software Kosova http://www.flossk.org
Saving Wikipedia(tm) articles from deletion http://SpeedyDeletion.wikia.com

**Comment by h4ck3rm1k3** [comment]
This is rebased onto the current master and squashed into one commit.

**Pull request merged**
