### PR TITLE
neo4j from docker

### PR DESCRIPTION
**Pull request by borgified**

### CODE REVIEW

**Comment by Alan-R** [comment]
Here's the config line in no4j.conf that we need for some of our queries to run correctly:
cypher.forbid_shortestpath_common_nodes=false

See also: https://neo4j.com/docs/operations-manual/current/reference/configuration-settings/#config_cypher.forbid_shortestpath_common_nodes

**Comment by borgified** [comment]
there ought to be some way to do that even if we use a docker container for neo4j.. ill investigate and let you know

**Comment by borgified** [comment]
this is the way to do what we want:
```
 /conf volume

To make arbitrary modifications to the Neo4j configuration, provide the container with a /conf volume.

docker run \
    --detach \
    --publish=7474:7474 \
    --volume=$HOME/neo4j/data:/data \
    --volume=$HOME/neo4j/conf:/conf \
    neo4j:2.3.4
Any configuration files in the /conf volume will override files provided by the image. This includes values that may have been set in response to environment variables passed to the container by Docker. So if you want to change one value in a file you must ensure that the rest of the file is complete and correct.
```

so we need a location in the assimilation-official repo to store the default neo4j conf files. can you suggest the proper location in the repo for this?

**Comment by Alan-R** [comment]
What about buildtools/ci?

**Comment by Alan-R** [comment]
Also: I put a check in the release 2 code to verify that the configuration is set up according to our requirements.

**Pull request merged**
