### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by h4ck3rm1k3**
markdown for github

### CODE REVIEW

**Comment by h4ck3rm1k3** [comment]
this is a separate file so you don't have to change the readme.

**Comment by Alan-R** [comment]
But Doxygen supports Markdown, including Github extensions. So you should do this so that it replaces the existing README. https://www.stack.nl/~dimitri/doxygen/manual/markdown.html

**Comment by h4ck3rm1k3** [comment]
if you replace the existing readme, then just take my first patch, no?

**Comment by borgified** [comment]
i think the idea is to generate the markdown flavored readme rather than have to manually alter it

**Comment by Alan-R** [comment]
What I was asking for was to *replace* the existing README. So that
involves removing it, and pointing the web site content to the rendered
version of the README from a README.md file.

This would also involve changing this line: Welcome to the Assimilation
project. (README
<http://linux-ha.org/source-doc/assimilation/html/_r_e_a_d_m_e.html>) Coverity
Status <https://scan.coverity.com/projects/9> - proudly sponsored
by Assimilation Systems Limited <http://assimilationsystems.com/>.
to point at the new README rendered from the .md file.

On 09/16/2015 01:13 AM, Fwiffo wrote:
>
> i think the idea is to generate the markdown flavored readme rather
> than have to manually alter it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/assimilation/assimilation-official/pull/2#issuecomment-140651632>.
>


-- 

Alan Robertson / CTO
AlanR@AssimilationSystems.com <mailto:AlanR@AssimilationSystems.com>/ +1
303.947.7999

Assimilation Systems Limited
http://AssimilationSystems.com

Twitter <https://twitter.com/ossalanr> Linkedin
<https://www.linkedin.com/in/alanr> skype
<https://htmlsig.com/skype?username=alanr_unix.sh>

**Comment by borgified** [comment]
ah the other way then :)

**Comment by h4ck3rm1k3** [comment]
https://github.com/assimilation/assimilation-official/pull/1 Tested and works.

**Pull request closed without merging**
