### PR TITLE
Update docs to reflect migration to GitHub

### PR DESCRIPTION
**Pull request by borgified**
Is this more or less what you had in mind? I didn't get a chance to check it in doxygen yet. Probably good to check before merge.

### CODE REVIEW

**Comment by Alan-R** [comment]
I'll look at it in a bit. It turns out I was in that same file yesterday, and decided to update that while I was there. I didn't push mine upstream because of technical issues. I'll look at yours and then figure out how to do the merge. Or drop yours and include mine - after resolving my ssh key issues.

It also looks like yours failed build for some bizarre reason... I have no idea why. Something took 5 hours to complete...

**Comment by borgified** [comment]
i re-ran the build and it came through fine this time, i guess it must be travis-ci

**Comment by Alan-R** [comment]
Could you rebase your changes on the current base, and see what still needs to be done? I may have missed things, or you may have stated them better. If you like what's there now, feel free to close this item.

**Comment by borgified** [comment]
ok rebase done

**Pull request merged**
